[workspace]
members = ["core"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# zksnark = { git = "https://github.com/arkworks-rs/zksnark.git", branch = "main" }
