[workspace]
members = ["core", "macros", "provers/gnark"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
ruint = "1.16.0"
serde = { version = "1.0.219", features = ["derive"] }

rsnark-macros = { version = "0.1.0", path = "macros" }
