[package]
name = "rsnark-core"
version.workspace = true
edition.workspace = true

[dependencies]
ruint = { workspace = true, features = ["serde"] }
serde = { workspace = true }
rsnark-macros = { path = "../macros" }

[dev-dependencies]
serde_json = "1.0"
