[package]
name = "rsnark-provers-gnark"
version = "0.1.0"
edition = "2024"

[dependencies]
rust2go = { version = "0.4.1" }
thiserror = "2.0.11"

[build-dependencies]
rust2go = { version = "0.4.1", features = ["build"] }
